### ISSUE TITLE
Ability to change operational timeouts without code change

### ISSUE THREAD

**Issue by kvbanantha** [apiman/apiman#726]
Is it possible to set the timeout for every API request with out code changes and restarting the server?

**Comment by volkflo** [comment]
Sorry for the very late response. But in the meantime, we have a plugin for that. (https://github.com/apiman/apiman-plugins/tree/master/timeout-policy)

**Comment by mark-kumoco** [comment]
Hi, is there a version 2.0.0-Final of this policy? When I check the git repo (link above), it has 2.0.1-SNAPSHOT in the pom.xml file, which when I try and use in the add custom plugin page, it gets a 404 error.

		<groupId>io.apiman.plugins</groupId>
		<artifactId>apiman-plugins</artifactId>
		<version>2.0.1-SNAPSHOT</version>

I am running 2.0.0.-Final. Thanks.

**Comment by msavy** [comment]
Hi Mark. For some reason it looks like apiman-plugins-timeout-policy didn't make it into the Maven Central repository for the last release 🤔. I am not sure why; it's very strange and I will have to investigate to figure out how we can ensure that does not happen again. 

It looks like the tags were not applied properly to that repo or something.

As a workaround, you could build it yourself. Here's how:

```
git checkout 868e2a7690e7dbe4ce7c2f49c6dba66ef617bd8e
mvn clean install
```

You can use your local filesystem for plugins or  you could deploy it to your internal Maven repo or something.

Does that help?

**Comment by mark-kumoco** [comment]
I will try that tomorrow and let you know how I get on. Thanks for your prompt reply!!

**Comment by volkflo** [comment]
@msavy The policy is not in maven central because it was contributed by the community after we released apiman 2.0 :)

**Comment by msavy** [comment]
Aha, you are correct, Florian. I still don't know why the release version
tag is missing though. Will have to try to correct that.

> You might need to just build a more recent snapshot, Mark.


>
