### ISSUE TITLE
apiman.war deploy failed. Unable to instantiate ExceptionMapper

### ISSUE THREAD

**Issue by tevosouza** [apiman/apiman#814]
After the merge of #811 from @volkflo, I'm facing this error after build with 
`mvn clean install -Pinstall-all-wildfly10`

Am I doing anything wrong?

```
15:35:59,919 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("deploy") failed - address: ([("deployment" => "apiman.war")]) - failure description: {
    "WFLYCTL0080: Failed services" => {"jboss.undertow.deployment.default-server.default-host./apiman" => "org.jboss.msc.service.StartException in service jboss.undertow.deployment.default-server.default-host./apiman: java.lang.RuntimeException: RESTEASY003925: Unable to instantiate ExceptionMapper
    Caused by: java.lang.RuntimeException: RESTEASY003925: Unable to instantiate ExceptionMapper
    Caused by: org.jboss.weld.exceptions.AmbiguousResolutionException: WELD-001318: Cannot resolve an ambiguous dependency between: 
  - Managed Bean [class io.apiman.manager.api.rest.exceptions.mappers.RestExceptionMapper] with qualifiers [@Any @Default],
  - Managed Bean [class io.apiman.manager.api.rest.exceptions.mappers.RestExceptionMapper] with qualifiers [@Any @Default]"},
    "WFLYCTL0412: Required services that are not installed:" => ["jboss.undertow.deployment.default-server.default-host./apiman"],
    "WFLYCTL0180: Services with missing/unavailable dependencies" => undefined
}
```

**Comment by volkflo** [comment]
Hmmm this is strange, we didn't had any issue with tomcat. Maybe this is related to wildfly. I will take a look asap (hopefully in the next days).

**Comment by EricWittmann** [comment]
Ah yes - very likely there are now somehow multiple exception mappers for the same exception?  I would need to take a look at the code.  I'll try to do that today while doing other tasks.  :)

**Comment by EricWittmann** [comment]
I have fixed this here:  https://github.com/apiman/apiman/commit/7142d5bbd3b96e352a9a9e92d17de9c6c8566a51

The problem was with the new refactoring of the REST exceptions into their own module combined with how the BND (bundle) plugin works.  This is from the [BND plugin documentation](https://svn.apache.org/repos/asf/felix/releases/maven-bundle-plugin-1.2.0/doc/maven-bundle-plugin-bnd.html) (relevant part):

> The <Export-Package> instruction is a list of packages for the bundle to export. These packages are copied into the resulting bundle JAR file from the available classes (i.e., project classes, dependencies, and class path); thus, it is possible to include classes into your bundle that are not associated with source files in your project. <Export-Package> can be specified with package patterns using the '*' wildcard. Also, it is possible to exclude packages using negation by starting the package pattern with '!'. Thus, non-negated patterns indicate which of the available packages to include in the bundle, whereas negated patterns indicate which should not be included in the bundle.
> 
> The list of package patterns is ordered and earlier patterns are applied before later patterns. For example, if you specify "org.foo.*,!org.foo.impl" the second pattern has no effect since all org.foo packages have already been selected by the first pattern. Instead, you should specify "!org.foo.impl,org.foo.*", which will export all org.foo packages except org.foo.impl.

**Comment by volkflo** [comment]
@EricWittmann Really cool that you found the solution. Thank you a lot! :)

But one thing I still not understand is that tomcat did not thrown any execption on this. There it should be the same problem too?

**Comment by tevosouza** [comment]
@EricWittmann my hero! heheh
About the @volkflo comment, I'm very curious

**Comment by EricWittmann** [comment]
The reason is that in Tomcat we're not using classpath scanning to discover the JAX-RS classes (resource classes and exception mappers).  Instead, the JAX-RS application is configured using a JAX-RS `Application` class.  And in that class is where we list out all of the classes needed by our JAX-RS app.  The `RestExceptionMapper` class is one of the classes included in that collection.  Even though there are two of them on the classpath, it doesn't matter which one is actually used (they are the same).  Including a duplicate class on the classpath is obviously still not something you'd want to do...and it could get you in trouble potentially.  But in this case that class is only loaded once here:  https://github.com/apiman/apiman/blob/master/manager/api/war/tomcat8/src/main/java/io/apiman/manager/api/war/tomcat8/Tomcat8ApiManagerApplication.java#L65

But when running in e.g. WildFly, we use an empty `Application` class and just let classpath scanning do its thing to find all of the relevant JAX-RS classes:  https://github.com/apiman/apiman/blob/master/manager/api/rest-impl/src/main/java/io/apiman/manager/api/rest/impl/ApiManagerApplication.java

So in that context, having a duplicate class on the classpath is problematic because classpath scanning will find them both and realize they do the same thing...and then will fail because it doesn't know which one to use.  Note that I believe it would **also** fail if you had two exception mappers with different names but that handled the same exception class.

**Comment by volkflo** [comment]
Okay, I think I understand this now. Thank you for the detailed explanation. :)
It is good to know this if there are changes in the future.
